version: '3.8'

services:
    
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - ./rabbitmq/dados:/var/lib/rabbitmq

  # Serviço do Spring Boot
  backend:
    build:
      context: ./spring # Diretório do Spring Boot
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://database:3306/mydb # Caminho para o banco
      SPRING_DATASOURCE_USERNAME: root # Usuario para acesso ao banco
      SPRING_DATASOURCE_PASSWORD: example # Senha para acesso ao banco
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
    depends_on:
      - rabbitmq
      - database
    
  servidor:
    build:
      context: ./servidor
      dockerfile: Dockerfile
    container_name: servidor
    ports:
      - "5001:5001"
    volumes:
      - ./servidor:/app
    depends_on:
      - rabbitmq